---
# tasks file for ec2_launch
- name: Adding security group
  amazon.aws.ec2_group:
    name: afrin
    description: Security group for EC2 instance
    region: us-east-1
    rules: 
      - proto: tcp
        from_port: 3001
        to_port: 3001
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3000
        to_port: 3000
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: -1
        cidr_ip: 0.0.0.0/0
  register: security_group

- name: Launch instance
  amazon.aws.ec2_instance:
    name: ansible-test-instance
    key_name: "{{ ec2_key_name }}"
    region: "{{ aws_region }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_ami_id }}"
    security_group: "{{ security_group.group_id }}"
  register: ec2


- name: waiting for  instance to be ready
  wait_for:
    host: "{{ ec2.instances[0].public_dns_name }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  when: ec2.instances is defined and ec2.instances | length > 0

- name: add ec2 instance to dynamic inventory
  add_host:
    name: "{{ ec2.instances[0].public_dns_name }}"
    groups: launch_instance
    ansible_private_key_file: "{{ ec2_ssh_key_path }}"
    ansible_user: ec2-user

- name: Debug SSH key 
  debug:
    var: ec2_ssh_key_path

- name: debug dynamic inventory
  debug:
    var: groups['launch_instance']