---
- name: Provision ec2 and install xx
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Adding security group
      amazon.aws.ec2_group:
        name: default
        description: Security group fro ec2 instance
        region: us-east-1
        rules: 
          - proto: tcp
            from_port: 3001
            to_port: 3001
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 3000
            to_port: 3000
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: security_group