name: provision ec2  instance and cofigure
on:
    push:
        branches:
            - main

jobs:
    provision-ec2:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x' 
            - name: install dependancy
              run: |
                    python -m pip install --upgrade pip
                    pip install ansible boto3 botocore
                    ansible-galaxy collection install amazon.aws
